"""add reward ledger and redemptions tables

Revision ID: 07e54df91c64
Revises: bc1c23ce9842
Create Date: 2026-07-08 21:08:04.541180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e54df91c64'
down_revision: Union[str, Sequence[str], None] = 'bc1c23ce9842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('reward_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=100), nullable=True),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redemptions_id'), 'redemptions', ['id'], unique=False)
    op.create_index(op.f('ix_redemptions_user_id'), 'redemptions', ['user_id'], unique=False)
    op.create_table('reward_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['study_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_ledger_id'), 'reward_ledger', ['id'], unique=False)
    op.create_index(op.f('ix_reward_ledger_user_id'), 'reward_ledger', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reward_ledger_user_id'), table_name='reward_ledger')
    op.drop_index(op.f('ix_reward_ledger_id'), table_name='reward_ledger')
    op.drop_table('reward_ledger')
    op.drop_index(op.f('ix_redemptions_user_id'), table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_id'), table_name='redemptions')
    op.drop_table('redemptions')
    # ### end Alembic commands ###
